#!/usr/bin/env bash
# Generate the Homebrew formula for a released tag, on stdout.
#
#   ./scripts/gen-formula.sh v0.1.0 > Formula/dok.rb
#
# It reads the `.sha256` files the release workflow uploads next to each
# archive, so the checksums always match the artefacts people download —
# no manual hashing, nothing to forget after a retag.
set -euo pipefail

TAG=${1:?usage: gen-formula.sh <tag>   e.g. gen-formula.sh v0.1.0}
VERSION=${TAG#v}
REPO=${REPO:-alsaadii98/dok}
BASE="https://github.com/$REPO/releases/download/$TAG"

sha_for() {
  local target=$1
  local url="$BASE/dok-$VERSION-$target.tar.gz.sha256"
  local sum
  sum=$(curl -fsSL --retry 3 --retry-delay 2 "$url" | tr -d ' \n\r-')
  if [ ${#sum} -ne 64 ]; then
    echo "error: no valid sha256 at $url (got '${sum:0:80}')" >&2
    exit 1
  fi
  printf '%s' "$sum"
}

# macOS gets the gnu-free darwin builds; Linux uses musl so one archive works
# on glibc and Alpine alike. Plain variables, because macOS still ships bash 3.
SHA_MAC_ARM=$(sha_for aarch64-apple-darwin)
SHA_MAC_X86=$(sha_for x86_64-apple-darwin)
SHA_LNX_ARM=$(sha_for aarch64-unknown-linux-musl)
SHA_LNX_X86=$(sha_for x86_64-unknown-linux-musl)

cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/gen-formula.sh — do not edit by hand.
# Every tagged release regenerates this file with fresh checksums.
class Dok < Formula
  desc "Docker output, made readable - what eza is to ls"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "MIT"
  head "https://github.com/$REPO.git", branch: "main"

  on_macos do
    on_arm do
      url "$BASE/dok-$VERSION-aarch64-apple-darwin.tar.gz"
      sha256 "$SHA_MAC_ARM"
    end
    on_intel do
      url "$BASE/dok-$VERSION-x86_64-apple-darwin.tar.gz"
      sha256 "$SHA_MAC_X86"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/dok-$VERSION-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$SHA_LNX_ARM"
    end
    on_intel do
      url "$BASE/dok-$VERSION-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$SHA_LNX_X86"
    end
  end

  # \`brew install --HEAD\` builds from source and needs a toolchain; the
  # normal path installs the prebuilt binary and needs nothing at all.
  head do
    depends_on "rust" => :build
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      # Archives contain a single dok-<version>-<target>/ directory.
      root = Dir["dok-*"].find { |d| File.directory?(d) } || "."
      bin.install "#{root}/dok"
      doc.install "#{root}/README.md", "#{root}/CHANGELOG.md" if File.exist?("#{root}/README.md")
      generate_completions_from_executable(bin/"dok", "completions")
    end
  end

  test do
    assert_match "dok", shell_output("#{bin}/dok --version")

    # --demo renders a canned stack, so this works on a machine with no
    # Docker daemon (which is exactly what brew test runs on).
    output = shell_output("#{bin}/dok ps --demo --color=never --icons=none")
    assert_match "demo-shop", output

    # Without a daemon and without --demo it must fail loudly, not hang.
    output = shell_output("DOCKER_HOST=unix:///nonexistent #{bin}/dok ps 2>&1", 1)
    assert_match(/docker/i, output)
  end
end
EOF
